// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wizlvkauqxnepsstditr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indpemx2a2F1cXhuZXBzc3RkaXRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjExNTgzMzQsImV4cCI6MjA3NjczNDMzNH0.T6Fil8QeUxmD-N6uZ32i9r1YWQcDiK1gt9hTfssJFMw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});